In [1]:
# Pandas library import kar rahe hain data handle karne ke liye
import pandas as pd

In [2]:
# CSV file ko read karke dataframe me store kar rahe hain
ds = pd.read_csv("student.csv")

In [3]:
ds

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,Yes,5,2,36
4,7,75,No,8,5,66
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23
9996,7,64,Yes,8,5,58
9997,6,83,Yes,8,5,74
9998,9,97,Yes,7,0,95
9999,7,74,No,8,1,64

In [4]:
# Dataset ki basic information dekhne ke liye (columns, data types, null values)
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  int64
dtypes: int64(5), object(1)
memory usage: 468.9+ KB

In [5]:
# Duplicate rows check karne ke liye
ds.duplicated().sum()

np.int64(127)

In [6]:
# Duplicates Data ko drop karne ke liye
ds.drop_duplicates(inplace = True)

In [7]:
ds

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,Yes,5,2,36
4,7,75,No,8,5,66
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23
9996,7,64,Yes,8,5,58
9997,6,83,Yes,8,5,74
9998,9,97,Yes,7,0,95
9999,7,74,No,8,1,64

In [8]:
# Extracurricular Activities column me yes aur no ko numbers me convert kar rahe hain
# YES = 1, NO = 0
ds["Extracurricular Activities"] = ds["Extracurricular Activities"].replace(["Yes" , "No"] , [1 , 0])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3932\2533836475.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ds["Extracurricular Activities"] = ds["Extracurricular Activities"].replace(["Yes" , "No"] , [1 , 0])

In [9]:
ds

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91
1,4,82,0,4,2,65
2,8,51,1,7,2,45
3,5,52,1,5,2,36
4,7,75,0,8,5,66
...,...,...,...,...,...,...
9995,1,49,1,4,2,23
9996,7,64,1,8,5,58
9997,6,83,1,8,5,74
9998,9,97,1,7,0,95
9999,7,74,0,8,1,64

In [10]:
# columns ka name change kar rahy hain apni asani ke liye
ds.rename(columns={"Hours Studied" : "hour_studied" , 
                   "Previous Scores" : "previous_scores" , 
                   "Extracurricular Activities" : "extra_activities" , 
                   "Sleep Hours" : "sleep_hours" , 
                   "Sample Question Papers Practiced" : "past_paper_practiced" ,
                   "Performance Index" : "performance"} , inplace = True)

In [11]:
ds

,hour_studied,previous_scores,extra_activities,sleep_hours,past_paper_practiced,performance
0,7,99,1,9,1,91
1,4,82,0,4,2,65
2,8,51,1,7,2,45
3,5,52,1,5,2,36
4,7,75,0,8,5,66
...,...,...,...,...,...,...
9995,1,49,1,4,2,23
9996,7,64,1,8,5,58
9997,6,83,1,8,5,74
9998,9,97,1,7,0,95
9999,7,74,0,8,1,64

In [12]:
# Independent variables (features) select kar rahe hain (Performance ke ilawa sab)
x = ds.drop("performance" , axis = 1)

# Dependent variables (Target) select kar rahe hain (Only Performance)
y = ds["performance"]

In [13]:
# Dataset ko training aur testing me split karne ke liye function import kar rahe hain
from sklearn.model_selection import train_test_split

# 50% Training aur 50% Testing data bana rahe hain
X_train , X_test , y_train , y_test = train_test_split (x , y , test_size = 0.50 , random_state = 62)

In [14]:
# Linear Regression model import kar rahe hain
from sklearn.linear_model import LinearRegression

In [15]:
# Model create kar rahe hain
model = LinearRegression()

# Training data par model train (fit) kar rahe hain
model.fit(X_train , y_train)

LinearRegression()

In [16]:
# Model ka Coefficient dekhne ke liye
model.coef_

array([2.85988133, 1.01704287, 0.56792216, 0.49377887, 0.19777271])

In [17]:
# Model ka Interceopt dekhny ke liye
model.intercept_

np.float64(-34.11895370374136)

In [18]:
# Training data par predictions nikal rahe hain
y_pred_train = model.predict(X_train)

In [19]:
from sklearn.metrics import mean_squared_error , r2_score
from math import sqrt

In [20]:
# Training data ka Mean Squared Error calculate kar rahe hain
mean_squared_error(y_train , y_pred_train)

4.208789215233981

In [21]:
# Training data ka Root Mean Squared Error calculate kar rahe hain
sqrt(mean_squared_error(y_train , y_pred_train))

2.051533381457387

In [22]:
# Training data ka R2_Score calculate kar rahe hain
r2_score(y_train , y_pred_train)

0.988599894237448

In [23]:
# Testing data par predictions nikal rahe hain
y_pred_test = model.predict(X_test)

In [24]:
# Testing data ka Mean Squared Error calculate kar rahe hain
mean_squared_error(y_test , y_pred_test)

4.14794628623326

In [25]:
# Testing data ka root Mean Squared Error calculate kar rahe hain
sqrt(mean_squared_error(y_test , y_pred_test))

2.0366507521500243

In [26]:
# Testing data ka R2_Score calculate kar rahe hain
r2_score(y_test , y_pred_test)

0.9887486878389702

In [27]:
# User se Input le rahy hein
Hours_Studied         = float(input("Enter Hours Studied : "))
Previous_Scores      = float(input("Enter Previous Scores : "))
Extra_Activities     = int(input("Enter Extra Activities 1 or 0 : "))
Sleep_Hours          = float(input("Enter Sleep Hour : "))
Past_Paper_Practiced = int(input("Enter Past Paper Practiced 1 or 0 : "))

# Function bana rahy hein Charges Pridect karne ke liye
def Performance_Predictor(hours_studied , previous_scores , extra_activities , sleep_hours , past_paper_practiced):
    Performance = model.predict([[hours_studied , previous_scores , extra_activities , sleep_hours , past_paper_practiced]])
    return Performance
result = Performance_Predictor(Hours_Studied , Previous_Scores , Extra_Activities , Sleep_Hours , Past_Paper_Practiced)
print(result)

Enter Hours Studied :  12
Enter Previous Scores :  66
Enter Extra Activities 1 or 0 :  1
Enter Sleep Hour :  8
Enter Past Paper Practiced 1 or 0 :  1

[72.04037775]

C:\Users\Lenovo\anaconda2\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
ds['performance'].unique()