In [1]:
# Pandas library import kar rahe hain data handle karne ke liye
import pandas as pd

In [2]:
# CSV file ko read karke dataframe me store kar rahe hain
dt = pd.read_csv("insurance.csv")

In [3]:
dt

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
# Dataset ki basic information dekhne ke liye (columns, data types, null values)
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [5]:
# Duplicate rows check karne ke liye
dt.duplicated().sum()

np.int64(1)

In [6]:
# Duplicates Data ko drop karne ke liye
dt = dt.drop_duplicates()

In [7]:
dt

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [8]:
# Sex column me male aur female ko numbers me convert kar rahe hain
# male = 1, female = 0
dt["sex"] = dt["sex"].replace(["male" , "female"] , [1 , 0])

# Smoker column me yes aur no ko numbers me convert kar rahe hain
# yes = 1, no = 0
dt.smoker = dt["smoker"].replace(["yes" , "no"] , [1 , 0])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7152\2577515359.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dt["sex"] = dt["sex"].replace(["male" , "female"] , [1 , 0])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7152\2577515359.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt["sex"] = dt["sex"].replace(["male" , "female"] , [1 , 0])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7152\2577515359.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dt.smoker = dt["smoker"].replace(["yes" , "no"] , [1 , 0])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7152\2577515359.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt.smoker = dt["smoker"].replace(["yes" , "no"] , [1 , 0])

In [9]:
dt

      age  sex     bmi  children  smoker     region      charges
0      19    0  27.900         0       1  southwest  16884.92400
1      18    1  33.770         1       0  southeast   1725.55230
2      28    1  33.000         3       0  southeast   4449.46200
3      33    1  22.705         0       0  northwest  21984.47061
4      32    1  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    1  30.970         3       0  northwest  10600.54830
1334   18    0  31.920         0       0  northeast   2205.98080
1335   18    0  36.850         0       0  southeast   1629.83350
1336   21    0  25.800         0       0  southwest   2007.94500
1337   61    0  29.070         0       1  northwest  29141.36030

[1337 rows x 7 columns]

In [10]:
# Data ki Information nikalne ke liye 
dt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   int64
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   int64
 5   region    1337 non-null   object
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(4), object(1)
memory usage: 83.6+ KB

In [11]:
# Categorical variables ko numerical (0 aur 1) me convert karne ke liye get_dummies use kar rahe hain
dt = pd.get_dummies(dt  ,dtype = int)

In [12]:
dt

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,0,1
1,18,1,33.770,1,0,1725.55230,0,0,1,0
2,28,1,33.000,3,0,4449.46200,0,0,1,0
3,33,1,22.705,0,0,21984.47061,0,1,0,0
4,32,1,28.880,0,0,3866.85520,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
1333,50,1,30.970,3,0,10600.54830,0,1,0,0
1334,18,0,31.920,0,0,2205.98080,1,0,0,0
1335,18,0,36.850,0,0,1629.83350,0,0,1,0
1336,21,0,25.800,0,0,2007.94500,0,0,0,1
1337,61,0,29.070,0,1,29141.36030,0,1,0,0

In [13]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1337 non-null   int64
 1   sex               1337 non-null   int64
 2   bmi               1337 non-null   float64
 3   children          1337 non-null   int64
 4   smoker            1337 non-null   int64
 5   charges           1337 non-null   float64
 6   region_northeast  1337 non-null   int64
 7   region_northwest  1337 non-null   int64
 8   region_southeast  1337 non-null   int64
 9   region_southwest  1337 non-null   int64
dtypes: float64(2), int64(8)
memory usage: 114.9 KB

In [14]:
# Independent variables (features) select kar rahe hain (Charges ke ilawa sab)
x = dt.drop("charges" , axis = 1)

# Dependent variables (Target) select kar rahe hain (Only Charges)
y = dt.charges

In [15]:
# Dataset ko training aur testing me split karne ke liye function import kar rahe hain
from sklearn.model_selection import train_test_split

# 70% Training aur 30% Testing data bana rahe hain
X_train , X_test , y_train , y_test = train_test_split(x , y , test_size = 0.30 , random_state = 53)

In [16]:
# Linear Regression model import kar rahe hain
from sklearn.linear_model import LinearRegression

# Model create kar rahe hain
model = LinearRegression()

# Training data par model train (fit) kar rahe hain
model.fit(X_train , y_train)

LinearRegression()

In [17]:
# Model ka Coefficient dekhne ke liye
model.coef_

array([  247.23195736,  -225.46033496,   316.01336047,   480.26430957,
       23676.0088198 ,   574.31076457,   443.73069387,  -660.0340144 ,
        -358.00744404])

In [18]:
# Model ka Interceopt dekhny ke liye
model.intercept_

np.float64(-11423.650990623155)

In [19]:
from sklearn.metrics import mean_squared_error , r2_score
from math import sqrt

In [20]:
# Training data par predictions nikal rahe hain
y_pred_train = model.predict(X_train)

In [21]:
# Training data ka Mean Squared Error calculate kar rahe hain
mean_squared_error(y_train , y_pred_train)

34559682.55618254

In [22]:
# Training data ka root Mean Squared Error calculate kar rahe hain
sqrt(mean_squared_error(y_train , y_pred_train))

5878.748383472671

In [23]:
# Training data ka R2_Score calculate kar rahe hain
r2_score(y_train , y_pred_train)

0.7477399090914336

In [24]:
# Testing data par predictions nikal rahe hain
y_pred_test = model.predict(X_test)

In [25]:
# Testing data ka Mean Squared Error calculate kar rahe hain
mean_squared_error(y_test , y_pred_test)

41402466.64233483

In [26]:
# Testing data ka root Mean Squared Error calculate kar rahe hain
sqrt(mean_squared_error(y_test , y_pred_test))

6434.474853656266

In [27]:
# Testing data ka R2_Score calculate kar rahe hain
r2_score(y_test , y_pred_test)

0.7539086013173985

In [28]:
# Function bana rahy hein Charges Pridect karne ke liye
def Charges_predictor(age , sex , bmi , child , smoker , northwest , southeast , northeast , southwest):
    charges = model.predict([[age , sex , bmi , child , smoker , northwest , southeast , northeast , southwest]])
    return charges

# User se Input le rahy hein
Sex       = int(input("Enter Sex 1 or 0 :"))
Age       = int(input("Enter Age :"))
BMI       = float(input("Enter BMI :"))
Child     = int(input("Enter Children :"))
Smoker    = int(input("Enter 1 or 0 :"))
Northwest = int(input("Enter 1 or 0 :"))
Southeast = int(input("Enter 1 or 0 :"))
Northeast = int(input("Enter 1 or 0 :"))
Southwest = int(input("Enter 1 or 0 :"))

# Function call kar ke result store kar rahe hein
result = Charges_predictor(Age, Sex, BMI, Child, Smoker, Northwest, Southeast, Northeast, Southwest)
print(result)

Enter Sex 1 or 0 : 1
Enter Age : 23
Enter BMI : 24.3
Enter Children : 0
Enter 1 or 0 : 1
Enter 1 or 0 : 1
Enter 1 or 0 : 0
Enter 1 or 0 : 0
Enter 1 or 0 : 0

[25966.66793749]

C:\Users\Lenovo\anaconda2\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
dt